### PR TITLE
Don't modify kleene attr on failing match

### PR DESCRIPTION
**Pull request by redbaron**

### CODE REVIEW

**Comment by K-ballo** [comment]
If I understand your intent correctly, that is expected and desired behavior. You can avoid it by using `qi::hold[...]`, which pretty much does what your patch does but for any subject parser.

**Comment by K-ballo** [comment]
I realized we still haven't ported `qi::hold`, would you want to take care of that?

**Comment by djowel** [comment]
Yes, please do, Agustin! Many thanks. And yes, it is expected and desired behavior (for performance reasons).

**Comment by redbaron** [comment]
How can it be implemented using directive? Any directive doesn't see iterations of wrapped parser and only what it can see is a return value which is always true for kleene. So x3::hold[*(....)] will always do a copy.

I can see no other way to have clean state of attribute, other than updating it after evey successfull iteration. Without this patch last iteration (failing one) can partially update attribute and caller can do nothing about it.

**Comment by djowel** [comment]
yes, hold does a copy, uses that as the attribute and swaps on success. that has better performance because you only use it when needed and most of the time you don't need it (i.e. the default behaviour of the kleene is suitable in general). That has been the behaviour of Spirit-2. It works.

I might not be understanding your note about having a "clean state of attribute". It's best to present a use case that exhibits your needs.

[edit] Hmm, now I see what you mean. Kleene indeed always returns true, so yes, hold does not work for the kleene. That said, I still do not agree with the change of behavior from Spirit v2. Please present a use case why you want this behavior. There's a reason why there's a clear postcondition for parsers that states:

  On a failed match, attrib state is undefined.

http://www.boost.org/doc/libs/1_55_0/libs/spirit/doc/html/spirit/qi/reference/parser_concepts/parser.html

**Comment by redbaron** [comment]
I tried to create one, but completely failed to run test cases, Boost build system is too tricky for me ;( If you put some notes to README on how to run them it would be great.

Use case I am talking about is following:

``` cpp
TEST_CASE("kleene patch") {
    namespace x3 = boost::spirit::x3;
    const std::string input = "A\nB\nC";
    auto const p = *(x3::char_ >> x3::omit[x3::lit("\n")]);
    std::string attr;
    auto it = input.begin();
    CHECK((x3::parse(it, input.end(), p, attr)));
    CHECK(attr == "AB"); //it is ABC without patch
}
```

Basically the idea is that attribute must be updated only if parser under kleene operator succeeds.

**Comment by redbaron** [comment]
Basically I want to make parser to treat attributes in a similar way it treats iterator - failing match must revert it to the state of last successful match, otherwise it looks incorrect, that after return from kleene parser, iterator points to "C" ( == not yet parsed), but attribute already contain "C"!

**Comment by djowel** [comment]
Hrmmm... I don't know. It's too costly. You pay for it every time. On the other hand, the postcondition that I mentioned "On a failed match, attrib state is undefined", does not apply either, come to think of it, since kleene always succeeds. And there is no other way to get the behavior you want (currently). 

I imagine a multi-megabyte file of repeated stuff which fails at one point. Then, you want to have the attribute of the first N successful matches, instead of N+1.

**Comment by djowel** [comment]
Wait there's something wrong here. parse_into_container does a push_back only when successful. So there is no way for it to get a "C".

**Comment by redbaron** [comment]
One way to do it cheap is to make parsers to return "update object" and then  on success merge it ot attribute. Quick untested and very rough example:

``` cpp
template <typename Iterator, typename Context, typename Attribute>
bool parse(Iterator& first, Iterator const& last, Context const& context, Attribute& attr) const
{
    typename traits::update_object<Attribute>::type upd;
    while (detail::parse_into_container(this->subject, first, last, upd)) {
        traits::merge(attr, upd);
        traits::reset(upd);
    }
}
...
template<class T, Enable = void>
struct update_object {
    using type = T;
}

namespace traits {
template<class Attr, class Upd>
void merge(Attr& attr, const Upd& upd) {};

template<>
void merge<std::string, std::string>(std::string& attr, const std::string& upd) {
    attr.append(upd);
}
...
template<>
void reset<std::string>(std::string& upd) {
  upd.clear();
}
}
```

**Comment by redbaron** [comment]
Attribute is updated when x3::sequence<>::parse is called  which itself calls this->left and passes attribute. At that point none of them are aware of kleene parser up the tree and happily update attribute.

**Comment by djowel** [comment]
That is correct, however the attribute passed to sequence is a temporary that gets pushed_back to the container _only_ on a successful parse. Check out parse_into_container:

https://github.com/djowel/spirit_x3/blob/master/boost/spirit/home/x3/core/detail/parse_into_container.hpp

As usual, best provide a minimal self-contained cpp file that exhibits your problem.

**Comment by redbaron** [comment]
there are 2 nested parse_into_container calls:
1. from kleene::parse (parser arg is sequence<>)
2. from sequence::parse (parser arg is this->left, which is x3::any_char in my test case)

and it is the latter one which updates attribute.

I'll post self containing example in a moment

**Comment by redbaron** [comment]
cpp file demonstrating the problem: https://gist.github.com/redbaron/9610165

**Comment by redbaron** [comment]
problem is that there is specialization of parse_into_container_impl<> for sequence<> which doesn't check for parse success always passing attribute to nested parsers as is

**Comment by djowel** [comment]
Confirmed. You've uncovered a bug.

**Comment by redbaron** [comment]
Updated pull request with fix for my case

**Comment by redbaron** [comment]
If I only was able to run unit tests, I could have provided better patches. :-/ https://github.com/djowel/spirit_x3/issues/7

**Comment by djowel** [comment]
I'm not sure how I can help you with bjam. Have you tried the tutorials? Can you run the full boost test suite?

**Comment by djowel** [comment]
wait, i'm wrong. your fix is probably correct. at that point, we know attr is already a container. It's not optimal though. Allow me to find a better fix.

**Comment by djowel** [comment]
nah, i think your fix is as optimal as it can get. i'm applying your fix and run the tests to make sure all is OK.

**Pull request merged**
